logo: ""
title: Enjoy The Moment, Enjoy The Love...
description: > # this means to ignore newlines until "baseurl:"
  Краткие заметки об удивительных местах для жаждущих странствий людей. Let's see the world through my eyes, enjoying every moment and love.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Christina Kuleshevich
about-author: Краткие заметки об удивительных местах для жаждущих странствий людей. Let's see the world through my eyes, enjoying every moment and love.# about author
email: christina@kuleshevi.ch
phone: # your pnone number
website: http://christina.kuleshevi.ch/ # you website

# Social link
instagram_url: https://www.instagram.com/kristy__si/ # add url link
vk_url: https://vk.com/id142796500 # add url link
facebook_url: https://www.facebook.com/profile.php?id=100003434916643&ref=bookmarks # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
