logo: ""
title: Enjoy The Moment of Travel
description: > # this means to ignore newlines until "baseurl:"
  Краткие заметки об удивительных местах для жаждущих странствий людей. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Christina Kuleshevich
about-author: Всем привет! Меня зовут Кристина. Я родилась в небольшом городе Слониме, расположенном на западе Беларуси. Конечно же с детства во мне живет мечта объездить весь мир, увидеть Новые чудеса света и изучить удивительные природные уголки нашей планеты. Пока я только делаю первые шаги на пути к ее достижению вместе со своим любимым мужем. На страничках своего блога, я буду делиться с вами своими открытиями, впечатлениями и эмоциями, которые я получила в разных странах; постараюсь помочь вам осуществить свою мечту путешественника. See the world through my eyes, enjoying every moment...
email: christina@kuleshevi.ch
phone: # your pnone number
website: http://christina.kuleshevi.ch/ # you website

# Social link
instagram_url: https://www.instagram.com/kristy__si/ # add url link
vk_url: https://vk.com/id142796500 # add url link
facebook_url: https://www.facebook.com/profile.php?id=100003434916643&ref=bookmarks # add url link
linkedin_url: https://www.linkedin.com/in/кристина-кулешевич

# Disqus
discus_identifier: christina-kuleshevich # add your discus identifier

# Newsletter
mailchimp: https://kuleshevi.us19.list-manage.com/subscribe/post?u=9221a69e7dbccb59e0b67ca5d&amp;id=3b51b74e14

# Tracker
analytics: 

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
